# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(max_length=10)),
                ('profshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profshow')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitsid', models.CharField(max_length=15)),
                ('qr_code', models.CharField(max_length=10)),
                ('no_of_enteries', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='qrcode',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
    ]
