# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180420_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(max_length=10)),
                ('number', models.IntegerField(default=0)),
                ('profshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profshow')),
            ],
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='profshow',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='no_of_enteries',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Qrcode',
        ),
        migrations.AddField(
            model_name='tickets',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
    ]
